version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
    ports:
      - "3306:3306"
    restart: always
    
  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
